### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by JosephShering** [iron-io/functions#671]
When going through the readme on MAC OS X running the command

`fn apps create myapp` 

throws a

`panic: runtime error: invalid memory address or nil pointer dereference`

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x158c628]

goroutine 1 [running]:
github.com/iron-io/functions/fn/commands.(*appsCmd).create(0xc42051c090, 0xc4200ddb80, 0x1, 0x16e49ff)
	/home/ubuntu/go/src/github.com/iron-io/functions/fn/commands/apps.go:144 +0x2a8
github.com/iron-io/functions/fn/commands.(*appsCmd).(github.com/iron-io/functions/fn/commands.create)-fm(0xc4200ddb80, 0x0, 0xc420413e00)
	/home/ubuntu/go/src/github.com/iron-io/functions/fn/commands/apps.go:36 +0x34
github.com/iron-io/functions/vendor/github.com/urfave/cli.HandleAction(0x1613380, 0xc4204135f0, 0xc4200ddb80, 0x1, 0x0)
	/home/ubuntu/go/src/github.com/iron-io/functions/vendor/github.com/urfave/cli/app.go:485 +0xd4
github.com/iron-io/functions/fn/app.prepareCmdArgsValidation.func1(0xc4200ddb80, 0x0, 0xc4200ddb80)
	/home/ubuntu/go/src/github.com/iron-io/functions/fn/app/app.go:120 +0x357
github.com/iron-io/functions/vendor/github.com/urfave/cli.HandleAction(0x1613380, 0xc4203e28c0, 0xc4200ddb80, 0xc420071300, 0x0)
	/home/ubuntu/go/src/github.com/iron-io/functions/vendor/github.com/urfave/cli/app.go:485 +0xd4
github.com/iron-io/functions/vendor/github.com/urfave/cli.Command.Run(0x16e624f, 0x6, 0x0, 0x0, 0xc420413670, 0x1, 0x1, 0x16f0083, 0x10, 0x0, ...)
	/home/ubuntu/go/src/github.com/iron-io/functions/vendor/github.com/urfave/cli/command.go:193 +0xb72
github.com/iron-io/functions/vendor/github.com/urfave/cli.(*App).RunAsSubcommand(0xc4200f9860, 0xc4200dd900, 0x0, 0x0)
	/home/ubuntu/go/src/github.com/iron-io/functions/vendor/github.com/urfave/cli/app.go:374 +0xacc
github.com/iron-io/functions/vendor/github.com/urfave/cli.Command.startApp(0x16e406e, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x16f2b57, 0x13, 0x0, ...)
	/home/ubuntu/go/src/github.com/iron-io/functions/vendor/github.com/urfave/cli/command.go:280 +0x824
github.com/iron-io/functions/vendor/github.com/urfave/cli.Command.Run(0x16e406e, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x16f2b57, 0x13, 0x0, ...)
	/home/ubuntu/go/src/github.com/iron-io/functions/vendor/github.com/urfave/cli/command.go:79 +0x14c7
github.com/iron-io/functions/vendor/github.com/urfave/cli.(*App).Run(0xc4200f96c0, 0xc42000e280, 0x4, 0x4, 0x0, 0x0)
	/home/ubuntu/go/src/github.com/iron-io/functions/vendor/github.com/urfave/cli/app.go:250 +0x7d0
main.main()
	/home/ubuntu/go/src/github.com/iron-io/functions/fn/main.go:10 +0x53
```

**Comment by sss0350** [comment]
Looks like the same issue I ask before , check it out: 
https://github.com/iron-io/functions/issues/665

**Comment by JosephShering** [comment]
It's similar sure, but I tried to change the API_URL with no avail. I get a parse error for `127.0.0.1:8082`

**Comment by c0ze** [comment]
@JosephShering 

can you try `API_URL=http://127.0.0.1:8082 fn`
(yeah `http` protocol prefix is necessary.)

Also, have you checked your version ? `fn version`  ?

**Comment by raky35** [comment]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x46a74b0]

goroutine 120 [running]:
github.com/ethereum/go-ethereum/eth/filters.(*EventSystem).eventLoop(0xc42186ac80)
	/Users/travis/gopath/src/github.com/ethereum/go-ethereum/eth/filters/filter_system.go:434 +0x330

**Comment by c0ze** [comment]
@raky35 can you please provide little bit more information ? Your system, fn tool version, your application context etc ? (which command you run when you get the message etc ? what are API_URL env variables if passed ?)

As a side note, `ethereum` source is not referenced anywhere in the IF code base. I think your problem is not related to iron functions.

**Comment by sekullbe** [comment]
This is an old issue, but I found it googling for a solution to a panic crash while running 'fn apps create myapp' as well.  I had the container running on a different port and specifying a correct API_URL fixed the problem.
Just hoping to help the next person who comes along :)
